export type ServiceLocale = "en" | "es";
export type StrategicServiceKey = "growth" | "partnerships" | "commercial" | "change";

export type StrategicServiceCopy = {
  key: StrategicServiceKey;
  locale: ServiceLocale;
  slug: string;
  counterpartSlug: string;
  seoTitle: string;
  seoDescription: string;
  schemaName: string;
  schemaType: string;
  breadcrumb: string;
  eyebrow: string;
  title: string;
  accent: string;
  lead: string;
  primary: string;
  asideTitle: string;
  aside: readonly string[];
  challengeTitle: string;
  challengeBody: string;
  capabilitiesTitle: string;
  capabilitiesLead: string;
  capabilities: readonly (readonly [string, string])[];
  momentsTitle: string;
  moments: readonly (readonly [string, string])[];
  approachTitle: string;
  approach: readonly (readonly [string, string])[];
  methodNote: string;
  deliverablesTitle: string;
  deliverables: readonly string[];
  differenceTitle: string;
  differenceBody: string;
  proof: readonly (readonly [string, string])[];
  proofNote: string;
  faq: readonly (readonly [string, string])[];
  conversationTitle: string;
  conversationBody: string;
  whatsapp: string;
};

export const strategicServices: Record<StrategicServiceKey, Record<ServiceLocale, StrategicServiceCopy>> = {
  growth: {
    en: {
      key: "growth", locale: "en", slug: "business-growth-strategy", counterpartSlug: "estrategia-negocio-crecimiento",
      seoTitle: "Healthcare Business & Growth Strategy Mexico & LATAM | Accesslerate",
      seoDescription: "Operator-led healthcare business and growth strategy for Mexico and Latin America—from opportunity and portfolio choices to go-to-market and organizational activation.",
      schemaName: "Healthcare Business and Growth Strategy Consulting", schemaType: "Business and Growth Strategy",
      breadcrumb: "Business & Growth Strategy", eyebrow: "BUSINESS & GROWTH STRATEGY · HEALTHCARE · MEXICO & LATIN AMERICA",
      title: "Growth is not a list of opportunities.", accent: "It is a set of choices.",
      lead: "We help healthcare leaders focus the growth agenda, choose where to play and build the commercial and organizational path required to win across Mexico and Latin America.",
      primary: "Discuss your growth question", asideTitle: "Designed for consequential choices",
      aside: ["Prioritizing a portfolio", "Entering a new market", "Reigniting stalled growth", "Building a go-to-market model"],
      challengeTitle: "More opportunities do not create a growth strategy. Better choices do.",
      challengeBody: "Sustainable growth requires a clear view of market potential, explicit portfolio and customer choices, credible economics and an organization aligned to execute the few moves that matter most.",
      capabilitiesTitle: "From growth ambition to a focused agenda.", capabilitiesLead: "We bring structure to the choices that determine where growth will come from and how it will be captured.",
      capabilities: [["Growth Strategy & Strategic Choices", "Define the ambition, where-to-play choices and competitive logic that focus leadership attention and investment."], ["Portfolio & Opportunity Assessment", "Compare markets, categories, assets and adjacencies through a common strategic and economic lens."], ["Market Entry & Go-to-Market Strategy", "Design a credible route to market around customers, channels, access realities and local capabilities."], ["Business Case & Growth Economics", "Translate strategic options into scenarios, assumptions, value pools and explicit investment decisions."], ["Growth Agenda & Change Activation", "Align leaders, governance, capabilities and first moves so the growth strategy becomes an operating agenda."]],
      momentsTitle: "When growth demands a sharper point of view.", moments: [["Growth has stalled.", "The current playbook is no longer creating momentum and the real constraint is unclear."], ["The portfolio needs focus.", "Too many possibilities are competing for investment, attention and organizational capacity."], ["A new market is in view.", "The opportunity looks attractive, but the entry model, economics and right to win need to be tested."], ["The strategy must land.", "The direction is clear, but ownership, capabilities and adoption will determine whether it produces growth."]],
      approachTitle: "Choose, build and mobilize.", approach: [["Frame", "Clarify the growth ambition, decision and constraints that matter."], ["Decode", "Distill market, customer, competitor and organizational signals."], ["Choose", "Prioritize where to play, how to win and what not to pursue."], ["Build", "Translate choices into economics, a go-to-market model and roadmap."], ["Mobilize", "Align leadership, owners, capabilities and measurable first moves."]], methodNote: "Strategy and change methods adapted to context: scenario planning · Agile · Prosci ADKAR",
      deliverablesTitle: "A growth agenda leaders can use.", deliverables: ["Growth thesis and strategic choices", "Portfolio and opportunity prioritization", "Market and customer attractiveness map", "Go-to-market blueprint", "Business case and investment scenarios", "Activation roadmap and governance"],
      differenceTitle: "Operator judgment. External clarity.", differenceBody: "Accesslerate combines rigorous strategic thinking with the practical judgment of a healthcare operator. Yuriko Tovar leads every engagement directly, drawing on 20+ years building growth, access, commercial models and organizational change across Mexico and Latin America.", proof: [["20+", "Years across healthcare"], ["+300%", "Patient-base growth"], ["8→20%", "Market-share growth"]], proofNote: "Selected outcomes reflect Yuriko Tovar’s prior executive roles.",
      faq: [["What does a healthcare growth strategy include?", "It connects market and customer insight with explicit portfolio, market-entry, go-to-market, investment and capability choices. The output is a focused agenda with owners and decisions, not a long list of opportunities."], ["Can Accesslerate support market entry in Mexico or Latin America?", "Yes. We assess attractiveness, access and commercial realities, route-to-market options, partnership needs, economics and organizational readiness for Mexico and selected Latin American markets."], ["How do you prioritize growth opportunities?", "We use a common set of strategic, market, economic and execution criteria so leaders can compare opportunities transparently and focus resources."], ["Do you work with established companies and investors?", "Yes. We support Pharma, Biotech, Consumer Health, MedTech, Diagnostics, Health Services, investors and innovators when the decision requires healthcare operator judgment."], ["How does Change Management fit into growth strategy?", "Growth choices often require new priorities, roles, capabilities and behaviors. We design leadership alignment, governance and adoption into the growth roadmap from the start."]],
      conversationTitle: "Bring us the growth question that matters most.", conversationBody: "In a focused 30-minute conversation, we will explore the decision, the stakes and whether Accesslerate is the right partner.", whatsapp: "Hello Yuriko, I would like to discuss a healthcare growth strategy challenge with Accesslerate.",
    },
    es: {
      key: "growth", locale: "es", slug: "estrategia-negocio-crecimiento", counterpartSlug: "business-growth-strategy",
      seoTitle: "Estrategia de Negocio y Crecimiento Healthcare México y LATAM | Accesslerate",
      seoDescription: "Estrategia de negocio y crecimiento para healthcare en México y Latinoamérica: oportunidades, portafolio, go-to-market y activación organizacional.",
      schemaName: "Consultoría de Estrategia de Negocio y Crecimiento Healthcare", schemaType: "Estrategia de Negocio y Crecimiento",
      breadcrumb: "Estrategia de Negocio y Crecimiento", eyebrow: "ESTRATEGIA DE NEGOCIO Y CRECIMIENTO · HEALTHCARE · MÉXICO Y LATINOAMÉRICA",
      title: "Crecer no es acumular oportunidades.", accent: "Es elegir dónde ganar.",
      lead: "Ayudamos a líderes de healthcare a enfocar la agenda de crecimiento, elegir dónde competir y construir la ruta comercial y organizacional para ganar en México y Latinoamérica.",
      primary: "Conversemos sobre tu reto de crecimiento", asideTitle: "Diseñado para decisiones decisivas",
      aside: ["Priorizar un portafolio", "Entrar a un nuevo mercado", "Reactivar el crecimiento", "Construir un modelo go-to-market"],
      challengeTitle: "Más oportunidades no construyen una estrategia de crecimiento. Mejores decisiones, sí.",
      challengeBody: "El crecimiento sostenible exige una lectura clara del potencial, decisiones explícitas de portafolio y clientes, una lógica económica creíble y una organización alineada alrededor de los movimientos que más importan.",
      capabilitiesTitle: "De la ambición de crecimiento a una agenda enfocada.", capabilitiesLead: "Damos estructura a las decisiones que determinan de dónde vendrá el crecimiento y cómo capturarlo.",
      capabilities: [["Estrategia de Crecimiento y Decisiones Estratégicas", "Definimos la ambición, dónde jugar y la lógica competitiva para enfocar la atención y la inversión."], ["Evaluación de Portafolio y Oportunidades", "Comparamos mercados, categorías, activos y adyacencias bajo una misma lógica estratégica y económica."], ["Entrada a Mercado y Estrategia Go-to-Market", "Diseñamos una ruta basada en clientes, canales, realidades de acceso y capacidades locales."], ["Business Case y Economía del Crecimiento", "Traducimos opciones en escenarios, supuestos, fuentes de valor y decisiones explícitas de inversión."], ["Agenda de Crecimiento y Activación del Cambio", "Alineamos líderes, gobernanza, capacidades y primeros movimientos para convertir la estrategia en agenda operativa."]],
      momentsTitle: "Cuando crecer exige una perspectiva más precisa.", moments: [["El crecimiento se estancó.", "El playbook actual ya no genera impulso y la restricción real no está clara."], ["El portafolio necesita foco.", "Demasiadas posibilidades compiten por inversión, atención y capacidad organizacional."], ["Existe un nuevo mercado.", "La oportunidad parece atractiva, pero deben probarse el modelo de entrada, la economía y el derecho a ganar."], ["La estrategia debe aterrizar.", "La dirección está clara, pero la responsabilidad, las capacidades y la adopción definirán el crecimiento."]],
      approachTitle: "Elegir, construir y movilizar.", approach: [["Enmarcar", "Aclarar la ambición, la decisión y las restricciones relevantes."], ["Decodificar", "Convertir señales de mercado, clientes, competencia y organización en insights."], ["Elegir", "Priorizar dónde jugar, cómo ganar y qué no perseguir."], ["Construir", "Traducir las decisiones en economía, modelo go-to-market y roadmap."], ["Movilizar", "Alinear liderazgo, responsables, capacidades y primeros movimientos medibles."]], methodNote: "Métodos de estrategia y cambio adaptados al contexto: escenarios · Agile · Prosci ADKAR",
      deliverablesTitle: "Una agenda de crecimiento que el liderazgo puede usar.", deliverables: ["Tesis de crecimiento y decisiones estratégicas", "Priorización de portafolio y oportunidades", "Mapa de atractivo de mercados y clientes", "Blueprint go-to-market", "Business case y escenarios de inversión", "Roadmap de activación y gobernanza"],
      differenceTitle: "Criterio de operadora. Claridad externa.", differenceBody: "Accesslerate combina pensamiento estratégico riguroso con el criterio práctico de quien ha operado dentro de healthcare. Yuriko Tovar lidera directamente cada proyecto, con más de 20 años construyendo crecimiento, acceso, modelos comerciales y cambio organizacional en México y Latinoamérica.", proof: [["20+", "Años en healthcare"], ["+300%", "Crecimiento de base de pacientes"], ["8→20%", "Crecimiento de market share"]], proofNote: "Resultados seleccionados de roles ejecutivos previos de Yuriko Tovar.",
      faq: [["¿Qué incluye una estrategia de crecimiento en healthcare?", "Conecta insights de mercado y clientes con decisiones explícitas de portafolio, entrada, go-to-market, inversión y capacidades. El resultado es una agenda enfocada con responsables y decisiones, no una lista extensa de oportunidades."], ["¿Accesslerate puede apoyar una entrada a México o Latinoamérica?", "Sí. Evaluamos atractivo, realidades de acceso y comerciales, rutas al mercado, necesidades de alianzas, economía y preparación organizacional para México y mercados seleccionados de Latinoamérica."], ["¿Cómo priorizan oportunidades de crecimiento?", "Usamos criterios estratégicos, de mercado, económicos y de ejecución comunes para comparar oportunidades con transparencia y enfocar recursos."], ["¿Trabajan con empresas establecidas e inversionistas?", "Sí. Apoyamos a Pharma, Biotech, Consumer Health, MedTech, Diagnóstico, Servicios de Salud, inversionistas e innovadores cuando la decisión requiere criterio operativo de healthcare."], ["¿Cómo se integra Gestión del Cambio?", "Las decisiones de crecimiento suelen exigir nuevas prioridades, roles, capacidades y comportamientos. Diseñamos alineación de líderes, gobernanza y adopción desde el inicio."]],
      conversationTitle: "Tráenos la pregunta de crecimiento que más importa.", conversationBody: "En una conversación enfocada de 30 minutos exploraremos la decisión, lo que está en juego y si Accesslerate es el socio adecuado.", whatsapp: "Hola Yuriko, me gustaría conversar sobre un reto de estrategia de crecimiento en healthcare con Accesslerate.",
    },
  },
  partnerships: {
    en: {
      key: "partnerships", locale: "en", slug: "new-business-partnerships", counterpartSlug: "nuevos-negocios-alianzas",
      seoTitle: "Healthcare Business Development & Partnerships LATAM | Accesslerate", seoDescription: "Healthcare new business development and partnership strategy across Mexico and Latin America—from opportunity scouting and assessment to partner activation.",
      schemaName: "Healthcare New Business Development and Partnerships Consulting", schemaType: "New Business Development and Partnership Strategy", breadcrumb: "New Business & Partnerships",
      eyebrow: "NEW BUSINESS & PARTNERSHIPS · HEALTHCARE · MEXICO & LATIN AMERICA", title: "The right opportunity creates momentum.", accent: "The right partnership sustains it.",
      lead: "We help healthcare companies identify, assess and activate new business opportunities and partnerships that can create sustainable growth across Mexico and Latin America.", primary: "Discuss a new business opportunity", asideTitle: "Designed for pivotal growth moves", aside: ["Building an opportunity pipeline", "Selecting a local partner", "Testing strategic fit", "Activating a signed partnership"],
      challengeTitle: "A promising opportunity is not yet a business. A signed partner is not yet momentum.", challengeBody: "Value is created when strategic fit, market realities, partner incentives, economics and execution are evaluated together—and when both organizations are mobilized around a shared path.",
      capabilitiesTitle: "From possibility to a partnership that can perform.", capabilitiesLead: "We connect opportunity discovery with the decisions, diligence and activation required to move.",
      capabilities: [["Opportunity Landscape & Scouting", "Build a focused view of adjacencies, assets, models and market opportunities aligned with the growth thesis."], ["Strategic Fit & Market Attractiveness", "Assess the opportunity through market, access, commercial, capability, risk and economic lenses."], ["Partner Strategy & Selection", "Define the ideal partner profile, evaluation criteria, engagement path and basis for mutual value."], ["Deal & Partnership Assessment", "Pressure-test strategic logic, assumptions, operating implications and the conditions required for success."], ["Activation, Governance & Change", "Translate the agreement into owners, decision rights, joint ways of working, milestones and adoption."]],
      momentsTitle: "When the next growth move depends on more than the deal.", moments: [["A new growth horizon is needed.", "The core business needs credible adjacencies, assets or models to create future value."], ["A local partner is essential.", "Market entry or expansion depends on finding the right capabilities, incentives and strategic fit."], ["The pipeline lacks focus.", "Opportunities are accumulating, but comparison criteria and investment priorities are unclear."], ["A partnership is underperforming.", "The agreement exists, but governance, ownership, trust or execution is limiting value."]],
      approachTitle: "Discover, assess and activate.", approach: [["Define", "Clarify the growth thesis, partner need and decision criteria."], ["Scan", "Build a targeted landscape of opportunities and potential partners."], ["Assess", "Test fit, attractiveness, economics, risks and execution requirements."], ["Shape", "Develop the partnership model, value exchange and decision agenda."], ["Activate", "Align owners, governance, milestones, capabilities and ways of working."]], methodNote: "Opportunity and change methods adapted to context: strategic screening · diligence · Agile activation",
      deliverablesTitle: "A decision-ready opportunity and activation path.", deliverables: ["Opportunity landscape and strategic thesis", "Screening criteria and prioritized pipeline", "Partner profile and targeted longlist", "Strategic and commercial assessment", "Business case and decision agenda", "Partnership activation and governance plan"],
      differenceTitle: "Business-development perspective with operator depth.", differenceBody: "Accesslerate evaluates opportunities through the realities of healthcare access, customers, commercial execution and organizational change—not only through market size. Yuriko Tovar brings 20+ years of local and regional operator experience to every engagement.", proof: [["20+", "Years across healthcare"], ["7", "Global healthcare companies"], ["5", "Healthcare sectors"]], proofNote: "Experience spans GSK, Bayer, Novartis, Johnson & Johnson, AbbVie, B. Braun and MSD.",
      faq: [["What does healthcare business development consulting include?", "It can include opportunity scouting, market and strategic assessment, partner strategy, commercial and operating diligence, business cases, decision support and partnership activation."], ["Can you help identify partners in Mexico or Latin America?", "Yes. We define the partner profile and evaluation logic, develop a targeted landscape and support the strategic assessment and engagement agenda."], ["Do you support licensing and distribution opportunities?", "We can assess the strategic, market, access, commercial and organizational logic of licensing, distribution, alliances and other partnership models. Legal and tax diligence remains with specialist advisors."], ["How do you assess strategic fit?", "We test alignment with the growth thesis, market attractiveness, access pathways, capabilities, economics, risk, partner incentives and execution feasibility."], ["Can you help after a partnership is signed?", "Yes. We design governance, decision rights, milestones, joint ways of working and the Change Management needed to turn the agreement into performance."]],
      conversationTitle: "Bring us the opportunity or partnership that could change the trajectory.", conversationBody: "In a focused 30-minute conversation, we will explore the strategic question, the market context and the next decision that matters.", whatsapp: "Hello Yuriko, I would like to discuss a healthcare new business or partnership opportunity with Accesslerate.",
    },
    es: {
      key: "partnerships", locale: "es", slug: "nuevos-negocios-alianzas", counterpartSlug: "new-business-partnerships",
      seoTitle: "Nuevos Negocios y Alianzas Healthcare México y LATAM | Accesslerate", seoDescription: "Desarrollo de nuevos negocios y estrategia de alianzas en healthcare para México y Latinoamérica: scouting, evaluación, selección y activación.",
      schemaName: "Consultoría de Nuevos Negocios y Alianzas Healthcare", schemaType: "Desarrollo de Nuevos Negocios y Estrategia de Alianzas", breadcrumb: "Nuevos Negocios y Alianzas",
      eyebrow: "NUEVOS NEGOCIOS Y ALIANZAS · HEALTHCARE · MÉXICO Y LATINOAMÉRICA", title: "La oportunidad correcta genera impulso.", accent: "La alianza correcta lo sostiene.",
      lead: "Ayudamos a compañías de healthcare a identificar, evaluar y activar nuevos negocios y alianzas capaces de crear crecimiento sostenible en México y Latinoamérica.", primary: "Conversemos sobre una oportunidad", asideTitle: "Diseñado para movimientos de crecimiento", aside: ["Construir un pipeline", "Seleccionar un socio local", "Probar el fit estratégico", "Activar una alianza firmada"],
      challengeTitle: "Una oportunidad prometedora todavía no es un negocio. Un socio firmado todavía no es impulso.", challengeBody: "El valor aparece cuando el fit estratégico, las realidades del mercado, los incentivos, la economía y la ejecución se evalúan en conjunto, y cuando ambas organizaciones se movilizan alrededor de una ruta compartida.",
      capabilitiesTitle: "De la posibilidad a una alianza que puede rendir.", capabilitiesLead: "Conectamos el descubrimiento con las decisiones, la evaluación y la activación necesarias para avanzar.",
      capabilities: [["Mapa de Oportunidades y Scouting", "Construimos una visión enfocada de adyacencias, activos, modelos y mercados alineados con la tesis de crecimiento."], ["Fit Estratégico y Atractivo de Mercado", "Evaluamos la oportunidad desde mercado, acceso, ejecución comercial, capacidades, riesgo y economía."], ["Estrategia y Selección de Socios", "Definimos perfil ideal, criterios de evaluación, ruta de acercamiento y base de valor mutuo."], ["Evaluación de Deals y Alianzas", "Ponemos a prueba la lógica, los supuestos, las implicaciones operativas y las condiciones de éxito."], ["Activación, Gobernanza y Cambio", "Traducimos el acuerdo en responsables, decisiones, formas de trabajo, hitos y adopción."]],
      momentsTitle: "Cuando el siguiente movimiento exige más que cerrar el deal.", moments: [["Se necesita un nuevo horizonte.", "El negocio principal requiere adyacencias, activos o modelos creíbles para crear valor futuro."], ["Un socio local es esencial.", "La entrada o expansión depende de capacidades, incentivos y fit estratégico adecuados."], ["El pipeline carece de foco.", "Las oportunidades se acumulan, pero faltan criterios y prioridades de inversión."], ["La alianza no está rindiendo.", "Existe el acuerdo, pero la gobernanza, responsabilidad, confianza o ejecución limitan el valor."]],
      approachTitle: "Descubrir, evaluar y activar.", approach: [["Definir", "Aclarar la tesis de crecimiento, la necesidad de socio y los criterios."], ["Explorar", "Construir un panorama dirigido de oportunidades y socios potenciales."], ["Evaluar", "Probar fit, atractivo, economía, riesgos y requisitos de ejecución."], ["Estructurar", "Desarrollar el modelo de alianza, el intercambio de valor y la agenda de decisión."], ["Activar", "Alinear responsables, gobernanza, hitos, capacidades y formas de trabajo."]], methodNote: "Métodos de oportunidad y cambio adaptados al contexto: screening estratégico · diligence · activación Agile",
      deliverablesTitle: "Una oportunidad lista para decidir y una ruta para activarla.", deliverables: ["Mapa de oportunidades y tesis estratégica", "Criterios y pipeline priorizado", "Perfil de socio y longlist dirigido", "Evaluación estratégica y comercial", "Business case y agenda de decisión", "Plan de activación y gobernanza"],
      differenceTitle: "Perspectiva de business development con profundidad operativa.", differenceBody: "Accesslerate evalúa oportunidades desde las realidades de acceso, clientes, ejecución comercial y cambio organizacional en healthcare, no solo desde el tamaño del mercado. Yuriko Tovar aporta más de 20 años de experiencia operativa local y regional.", proof: [["20+", "Años en healthcare"], ["7", "Compañías globales"], ["5", "Sectores de healthcare"]], proofNote: "Experiencia en GSK, Bayer, Novartis, Johnson & Johnson, AbbVie, B. Braun y MSD.",
      faq: [["¿Qué incluye una consultoría de nuevos negocios en healthcare?", "Puede incluir scouting, evaluación estratégica y de mercado, estrategia de socios, diligence comercial y operativa, business cases, soporte a decisiones y activación de alianzas."], ["¿Pueden ayudar a identificar socios en México o Latinoamérica?", "Sí. Definimos el perfil y la lógica de evaluación, construimos un panorama dirigido y apoyamos el análisis estratégico y la agenda de acercamiento."], ["¿Apoyan oportunidades de licenciamiento y distribución?", "Podemos evaluar la lógica estratégica, de mercado, acceso, comercial y organizacional de licencias, distribución, alianzas y otros modelos. La diligence legal y fiscal corresponde a especialistas."], ["¿Cómo evalúan el fit estratégico?", "Probamos alineación con la tesis, atractivo del mercado, rutas de acceso, capacidades, economía, riesgos, incentivos y viabilidad de ejecución."], ["¿Pueden ayudar después de firmar?", "Sí. Diseñamos gobernanza, decisiones, hitos, formas de trabajo y la Gestión del Cambio necesaria para convertir el acuerdo en desempeño."]],
      conversationTitle: "Tráenos la oportunidad o alianza que podría cambiar la trayectoria.", conversationBody: "En una conversación enfocada de 30 minutos exploraremos la pregunta estratégica, el contexto y la siguiente decisión relevante.", whatsapp: "Hola Yuriko, me gustaría conversar sobre una oportunidad de nuevos negocios o alianzas en healthcare con Accesslerate.",
    },
  },
  commercial: {
    en: {
      key: "commercial", locale: "en", slug: "commercial-transformation", counterpartSlug: "transformacion-comercial",
      seoTitle: "Healthcare Commercial Transformation Mexico & LATAM | Accesslerate", seoDescription: "Healthcare commercial transformation and operating-model strategy across Mexico and Latin America—customer engagement, capabilities, governance and adoption.",
      schemaName: "Healthcare Commercial Transformation Consulting", schemaType: "Commercial Model Transformation", breadcrumb: "Commercial Transformation",
      eyebrow: "COMMERCIAL TRANSFORMATION · HEALTHCARE · MEXICO & LATIN AMERICA", title: "A new strategy needs a commercial model", accent: "built for today.",
      lead: "We help healthcare leaders redesign customer engagement, roles, capabilities and governance around today’s access, channel and competitive realities—and activate the change required to perform.", primary: "Discuss your commercial model", asideTitle: "Designed for moments of reinvention", aside: ["Redesigning customer engagement", "Improving field productivity", "Integrating digital and human channels", "Landing a new operating model"],
      challengeTitle: "Commercial models lose relevance gradually—and performance suddenly.", challengeBody: "Transformation requires more than a new structure. Customer priorities, channels, roles, incentives, capabilities, data, governance and leadership behaviors must reinforce the same commercial choices.",
      capabilitiesTitle: "From commercial intent to a model that performs.", capabilitiesLead: "We redesign the system around the customer and mobilize the organization around the change.",
      capabilities: [["Customer & Engagement Strategy", "Define priority customer needs, engagement objectives, value exchange and the role of each channel."], ["Segmentation, Coverage & Channel Model", "Align segments, journeys, coverage, field deployment and digital interaction with opportunity and access realities."], ["Commercial Operating Model", "Clarify structure, roles, interfaces, governance and decision rights across commercial, access, medical and enabling functions."], ["Capabilities, Data & Performance", "Identify the skills, routines, insights and measures required to make the model work in practice."], ["Change Strategy & Adoption", "Align leaders, mobilize stakeholders and embed the new behaviors, ownership and ways of working."]],
      momentsTitle: "When the model no longer matches the market.", moments: [["Customer behavior has changed.", "The engagement model does not reflect how customers access information, make decisions or experience value."], ["Productivity must improve.", "Resources are active, but segmentation, coverage, roles or management routines are not translating into impact."], ["Digital remains fragmented.", "Channels have multiplied without one coherent journey, purpose or operating model."], ["A redesign is not landing.", "The target structure exists, but leaders, teams, capabilities and incentives have not moved with it."]],
      approachTitle: "Diagnose, redesign and embed.", approach: [["Diagnose", "Understand customer, market, access, performance and organizational realities."], ["Choose", "Define the commercial principles and explicit design choices."], ["Design", "Build the target journeys, coverage, operating model and governance."], ["Mobilize", "Align leaders, functions, capabilities, measures and incentives."], ["Embed", "Activate new routines and behaviors through adoption and learning loops."]], methodNote: "Transformation methods adapted to context: customer journeys · Agile design · Prosci ADKAR",
      deliverablesTitle: "A target model built to operate.", deliverables: ["Customer and market diagnosis", "Target engagement and channel model", "Segmentation and coverage blueprint", "Operating model, roles and decision rights", "Capability and performance roadmap", "Change, adoption and governance plan"],
      differenceTitle: "Commercial strategy grounded in operating reality.", differenceBody: "Accesslerate connects commercial design with market access, patient solutions and organizational change. Yuriko Tovar brings 20+ years of experience leading commercial operations and transformations inside global healthcare companies across Mexico and Latin America.", proof: [["+300%", "Patient-base growth"], ["30→90%", "Adherence improvement"], ["8→20%", "Market-share growth"]], proofNote: "Selected outcomes reflect Yuriko Tovar’s prior executive roles.",
      faq: [["What is healthcare commercial transformation?", "It is the redesign of how a healthcare company prioritizes and engages customers, deploys channels and resources, organizes roles, uses insights, manages performance and builds capabilities."], ["Does commercial transformation mean restructuring the sales force?", "Not necessarily. Structure is only one lever. The right answer may involve segmentation, journeys, coverage, access interfaces, digital channels, roles, governance, capabilities or management routines."], ["Can you integrate Market Access and Medical into the model?", "Yes. Healthcare customer and institutional decisions increasingly require clear cross-functional interfaces, governance and value exchange across Commercial, Market Access, Medical and other functions."], ["How do you make a new commercial model stick?", "We involve leaders and critical stakeholders early, translate design into specific roles and routines, build capabilities and measures, and manage adoption as part of the transformation."], ["Can you support a country or regional model?", "Yes. We can design for a local market, create regional principles with market flexibility, or help adapt a global model to Mexico and Latin American realities."]],
      conversationTitle: "Bring us the commercial question your current model cannot answer.", conversationBody: "In a focused 30-minute conversation, we will explore the market shift, the performance gap and the transformation that may be required.", whatsapp: "Hello Yuriko, I would like to discuss a healthcare commercial transformation challenge with Accesslerate.",
    },
    es: {
      key: "commercial", locale: "es", slug: "transformacion-comercial", counterpartSlug: "commercial-transformation",
      seoTitle: "Transformación Comercial Healthcare México y LATAM | Accesslerate", seoDescription: "Transformación comercial y diseño de modelo operativo en healthcare para México y Latinoamérica: engagement, capacidades, gobernanza y adopción.",
      schemaName: "Consultoría de Transformación Comercial Healthcare", schemaType: "Transformación del Modelo Comercial", breadcrumb: "Transformación Comercial",
      eyebrow: "TRANSFORMACIÓN COMERCIAL · HEALTHCARE · MÉXICO Y LATINOAMÉRICA", title: "Una nueva estrategia necesita un modelo comercial", accent: "diseñado para hoy.",
      lead: "Ayudamos a líderes de healthcare a rediseñar engagement, roles, capacidades y gobernanza alrededor de las realidades actuales de acceso, canales y competencia, y a activar el cambio requerido para rendir.", primary: "Conversemos sobre tu modelo comercial", asideTitle: "Diseñado para momentos de reinvención", aside: ["Rediseñar customer engagement", "Mejorar productividad de campo", "Integrar canales digitales y humanos", "Aterrizar un nuevo modelo operativo"],
      challengeTitle: "Los modelos comerciales pierden relevancia gradualmente y desempeño de manera repentina.", challengeBody: "Transformar exige más que una nueva estructura. Prioridades de clientes, canales, roles, incentivos, capacidades, datos, gobernanza y comportamientos de liderazgo deben reforzar las mismas decisiones comerciales.",
      capabilitiesTitle: "De la intención comercial a un modelo que rinde.", capabilitiesLead: "Rediseñamos el sistema alrededor del cliente y movilizamos a la organización alrededor del cambio.",
      capabilities: [["Estrategia de Clientes y Engagement", "Definimos necesidades prioritarias, objetivos de interacción, intercambio de valor y papel de cada canal."], ["Segmentación, Cobertura y Canales", "Alineamos segmentos, journeys, cobertura, despliegue de campo e interacción digital con la oportunidad y el acceso."], ["Modelo Operativo Comercial", "Clarificamos estructura, roles, interfaces, gobernanza y decisiones entre Comercial, Acceso, Médico y funciones habilitadoras."], ["Capacidades, Datos y Desempeño", "Identificamos habilidades, rutinas, insights y métricas necesarias para operar el modelo."], ["Estrategia de Cambio y Adopción", "Alineamos líderes, movilizamos stakeholders e instalamos comportamientos, ownership y formas de trabajo."]],
      momentsTitle: "Cuando el modelo ya no corresponde al mercado.", moments: [["El comportamiento cambió.", "El modelo no refleja cómo los clientes acceden a información, deciden o experimentan valor."], ["La productividad debe mejorar.", "Los recursos están activos, pero segmentación, cobertura, roles o rutinas no generan impacto."], ["Lo digital sigue fragmentado.", "Los canales se multiplicaron sin un journey, propósito o modelo operativo común."], ["El rediseño no aterriza.", "La estructura objetivo existe, pero líderes, equipos, capacidades e incentivos no se han movido."]],
      approachTitle: "Diagnosticar, rediseñar e instalar.", approach: [["Diagnosticar", "Entender clientes, mercado, acceso, desempeño y realidad organizacional."], ["Elegir", "Definir principios comerciales y decisiones explícitas de diseño."], ["Diseñar", "Construir journeys, cobertura, modelo operativo y gobernanza objetivo."], ["Movilizar", "Alinear líderes, funciones, capacidades, métricas e incentivos."], ["Instalar", "Activar nuevas rutinas y comportamientos mediante adopción y aprendizaje."]], methodNote: "Métodos de transformación adaptados al contexto: customer journeys · diseño Agile · Prosci ADKAR",
      deliverablesTitle: "Un modelo objetivo construido para operar.", deliverables: ["Diagnóstico de clientes y mercado", "Modelo objetivo de engagement y canales", "Blueprint de segmentación y cobertura", "Modelo operativo, roles y decisiones", "Roadmap de capacidades y desempeño", "Plan de cambio, adopción y gobernanza"],
      differenceTitle: "Estrategia comercial anclada en realidad operativa.", differenceBody: "Accesslerate conecta diseño comercial con market access, soluciones para pacientes y cambio organizacional. Yuriko Tovar aporta más de 20 años liderando operaciones y transformaciones comerciales dentro de compañías globales de healthcare en México y Latinoamérica.", proof: [["+300%", "Crecimiento de base de pacientes"], ["30→90%", "Mejora en adherencia"], ["8→20%", "Crecimiento de market share"]], proofNote: "Resultados seleccionados de roles ejecutivos previos de Yuriko Tovar.",
      faq: [["¿Qué es transformación comercial en healthcare?", "Es rediseñar cómo una compañía prioriza y relaciona clientes, despliega canales y recursos, organiza roles, usa insights, gestiona desempeño y construye capacidades."], ["¿Implica reestructurar la fuerza de ventas?", "No necesariamente. La estructura es solo una palanca. La respuesta puede involucrar segmentación, journeys, cobertura, interfaces de acceso, canales digitales, roles, gobernanza, capacidades o rutinas."], ["¿Pueden integrar Market Access y Medical?", "Sí. Las decisiones institucionales y de clientes requieren interfaces, gobernanza e intercambio de valor claros entre Comercial, Market Access, Medical y otras funciones."], ["¿Cómo logran que el modelo se adopte?", "Involucramos líderes y stakeholders desde etapas tempranas, traducimos el diseño en roles y rutinas, construimos capacidades y métricas, y gestionamos la adopción como parte de la transformación."], ["¿Pueden apoyar un modelo local o regional?", "Sí. Podemos diseñar para un mercado, crear principios regionales con flexibilidad local o adaptar un modelo global a México y Latinoamérica."]],
      conversationTitle: "Tráenos la pregunta comercial que tu modelo actual no puede responder.", conversationBody: "En una conversación enfocada de 30 minutos exploraremos el cambio de mercado, la brecha de desempeño y la transformación requerida.", whatsapp: "Hola Yuriko, me gustaría conversar sobre un reto de transformación comercial en healthcare con Accesslerate.",
    },
  },
  change: {
    en: {
      key: "change", locale: "en", slug: "change-management", counterpartSlug: "gestion-del-cambio",
      seoTitle: "Healthcare Change Management Consulting LATAM | Accesslerate", seoDescription: "Healthcare Change Management consulting across Mexico and Latin America—leadership alignment, stakeholder mobilization, capabilities and measurable adoption.",
      schemaName: "Healthcare Change Management Consulting", schemaType: "Change Management and Strategy Activation", breadcrumb: "Change Management",
      eyebrow: "CHANGE MANAGEMENT · STRATEGY ACTIVATION · HEALTHCARE · LATIN AMERICA", title: "Transformation succeeds when people", accent: "move with the strategy.",
      lead: "We help healthcare leaders turn strategic direction into organizational adoption through leadership alignment, stakeholder mobilization, capability building and measurable behavior change.", primary: "Discuss your transformation", asideTitle: "Designed for change that must land", aside: ["Activating a new strategy", "Redesigning an operating model", "Integrating teams or partners", "Reigniting a stalled transformation"],
      challengeTitle: "The strategy can be right and the transformation can still fail.", challengeBody: "Change is not the communication layer added after design. It is the leadership, stakeholder, capability, governance and behavior system that determines whether people can and will work differently.",
      capabilitiesTitle: "From strategic intent to sustained adoption.", capabilitiesLead: "Change Management is designed with the strategy so the organization is ready to move when the decision is made.",
      capabilities: [["Change Strategy & Readiness", "Define the change ambition, case for change, impacts, risks and organizational conditions required for success."], ["Leadership Alignment & Sponsorship", "Build shared direction, visible sponsorship, decision discipline and the leadership behaviors the change requires."], ["Stakeholder Mobilization", "Map influence, concerns and commitment; design meaningful involvement and communication around each group."], ["Capabilities, Behaviors & Adoption", "Translate the change into role-specific skills, routines, behaviors, tools and reinforcement mechanisms."], ["Governance, Measurement & Sustainability", "Create ownership, decision forums, adoption measures, feedback loops and actions that sustain momentum."]],
      momentsTitle: "When execution depends on people working differently.", moments: [["A new strategy is launching.", "Leaders understand the direction, but functions need clarity, ownership and coordinated first moves."], ["The operating model is changing.", "New structures and roles will only work if decision rights, interfaces and behaviors change too."], ["Teams or partners are integrating.", "Different incentives, cultures and ways of working must converge around shared outcomes."], ["Transformation has stalled.", "Activity continues, but sponsorship, belief, capability or reinforcement is not producing adoption."]],
      approachTitle: "Understand, align, activate and sustain.", approach: [["Frame", "Clarify the strategic outcome, change story and adoption required."], ["Listen", "Assess impacts, readiness, stakeholders, risks and organizational reality."], ["Align", "Mobilize leaders around decisions, sponsorship and shared behaviors."], ["Activate", "Equip teams through involvement, communication, capability and new routines."], ["Sustain", "Measure adoption, reinforce progress and adapt through feedback loops."]], methodNote: "Methods adapted—not imposed—to context: Kotter · Prosci ADKAR · Agile change",
      deliverablesTitle: "A practical system for organizational movement.", deliverables: ["Case for change and change strategy", "Impact and readiness assessment", "Stakeholder and influence map", "Leadership alignment and sponsor plan", "Communication, capability and adoption roadmap", "Governance and adoption scorecard"],
      differenceTitle: "Change led by someone who has carried the outcome.", differenceBody: "Yuriko Tovar has led growth, access, commercial and organizational transformations from inside global healthcare companies. Accesslerate brings that operator empathy to every engagement: respect for the strategy, realism about the organization and focus on measurable adoption.", proof: [["20+", "Years leading in healthcare"], ["3", "Adaptable change disciplines"], ["1", "Integrated strategy-and-change approach"]], proofNote: "Methodologies include Kotter, Prosci ADKAR and Agile, selected and adapted to the context.",
      faq: [["What is Change Management in healthcare?", "It is the structured work of helping leaders, teams and stakeholders understand, commit to, adopt and sustain the behaviors and ways of working required by a strategic or operational change."], ["Is Change Management mainly communication and training?", "No. Communication and training matter, but lasting change also requires leadership alignment, meaningful involvement, clear roles, capability, governance, measures and reinforcement."], ["Which Change Management methodology do you use?", "We draw from Kotter, Prosci ADKAR and Agile change practices. The method is adapted to the business challenge, organizational context and pace of change rather than applied as a rigid template."], ["How do you measure adoption?", "We define role-specific leading and lagging indicators such as awareness, commitment, readiness, capability, behavior, process usage, decision quality and business outcomes."], ["Can Change Management be integrated into a strategy or transformation project?", "Yes—and that is often where it creates the most value. We design the change implications, leadership alignment, stakeholder strategy and adoption roadmap alongside the strategic solution."]],
      conversationTitle: "Bring us the transformation that cannot afford to remain a presentation.", conversationBody: "In a focused 30-minute conversation, we will explore the strategic outcome, the human barriers and what adoption must look like.", whatsapp: "Hello Yuriko, I would like to discuss a healthcare Change Management challenge with Accesslerate.",
    },
    es: {
      key: "change", locale: "es", slug: "gestion-del-cambio", counterpartSlug: "change-management",
      seoTitle: "Consultoría Gestión del Cambio Healthcare LATAM | Accesslerate", seoDescription: "Gestión del Cambio para healthcare en México y Latinoamérica: alineación de líderes, movilización de stakeholders, capacidades y adopción medible.",
      schemaName: "Consultoría de Gestión del Cambio Healthcare", schemaType: "Gestión del Cambio y Activación Estratégica", breadcrumb: "Gestión del Cambio",
      eyebrow: "GESTIÓN DEL CAMBIO · ACTIVACIÓN ESTRATÉGICA · HEALTHCARE · LATINOAMÉRICA", title: "La transformación funciona cuando las personas", accent: "avanzan con la estrategia.",
      lead: "Ayudamos a líderes de healthcare a convertir dirección estratégica en adopción organizacional mediante alineación, movilización de stakeholders, desarrollo de capacidades y cambios de comportamiento medibles.", primary: "Conversemos sobre tu transformación", asideTitle: "Diseñado para cambios que deben aterrizar", aside: ["Activar una nueva estrategia", "Rediseñar un modelo operativo", "Integrar equipos o socios", "Reactivar una transformación"],
      challengeTitle: "La estrategia puede ser correcta y la transformación aun así puede fallar.", challengeBody: "El cambio no es la capa de comunicación que se agrega al final. Es el sistema de liderazgo, stakeholders, capacidades, gobernanza y comportamientos que determina si las personas pueden y quieren trabajar de otra manera.",
      capabilitiesTitle: "De la intención estratégica a la adopción sostenida.", capabilitiesLead: "Diseñamos Gestión del Cambio junto con la estrategia para que la organización esté lista cuando se tome la decisión.",
      capabilities: [["Estrategia de Cambio y Readiness", "Definimos ambición, caso para el cambio, impactos, riesgos y condiciones organizacionales de éxito."], ["Alineación de Liderazgo y Sponsorship", "Construimos dirección compartida, patrocinio visible, disciplina de decisión y comportamientos de liderazgo."], ["Movilización de Stakeholders", "Mapeamos influencia, preocupaciones y compromiso; diseñamos involucramiento y comunicación relevante."], ["Capacidades, Comportamientos y Adopción", "Traducimos el cambio en habilidades, rutinas, comportamientos, herramientas y refuerzos por rol."], ["Gobernanza, Medición y Sostenibilidad", "Creamos ownership, foros de decisión, métricas, loops de feedback y acciones que sostienen el impulso."]],
      momentsTitle: "Cuando ejecutar depende de trabajar de otra manera.", moments: [["Se lanza una nueva estrategia.", "Los líderes entienden la dirección, pero las funciones necesitan claridad, responsabilidad y primeros movimientos coordinados."], ["Cambia el modelo operativo.", "Nuevas estructuras y roles solo funcionarán si también cambian decisiones, interfaces y comportamientos."], ["Se integran equipos o socios.", "Diferentes incentivos, culturas y formas de trabajo deben converger alrededor de resultados compartidos."], ["La transformación se estancó.", "La actividad continúa, pero sponsorship, convicción, capacidad o refuerzo no generan adopción."]],
      approachTitle: "Entender, alinear, activar y sostener.", approach: [["Enmarcar", "Aclarar el resultado estratégico, la historia de cambio y la adopción requerida."], ["Escuchar", "Evaluar impactos, readiness, stakeholders, riesgos y realidad organizacional."], ["Alinear", "Movilizar líderes alrededor de decisiones, sponsorship y comportamientos."], ["Activar", "Equipar equipos mediante involucramiento, comunicación, capacidades y rutinas."], ["Sostener", "Medir adopción, reforzar progreso y adaptar con loops de feedback."]], methodNote: "Métodos adaptados—no impuestos—al contexto: Kotter · Prosci ADKAR · Agile change",
      deliverablesTitle: "Un sistema práctico para mover la organización.", deliverables: ["Caso y estrategia de cambio", "Evaluación de impactos y readiness", "Mapa de stakeholders e influencia", "Alineación de líderes y plan de sponsors", "Roadmap de comunicación, capacidades y adopción", "Gobernanza y scorecard de adopción"],
      differenceTitle: "Cambio liderado por quien ha cargado con el resultado.", differenceBody: "Yuriko Tovar ha liderado transformaciones de crecimiento, acceso, comerciales y organizacionales desde dentro de compañías globales de healthcare. Accesslerate aporta esa empatía de operadora: respeto por la estrategia, realismo sobre la organización y foco en adopción medible.", proof: [["20+", "Años liderando en healthcare"], ["3", "Disciplinas de cambio adaptables"], ["1", "Enfoque integrado de estrategia y cambio"]], proofNote: "Las metodologías incluyen Kotter, Prosci ADKAR y Agile, seleccionadas y adaptadas al contexto.",
      faq: [["¿Qué es Gestión del Cambio en healthcare?", "Es el trabajo estructurado para ayudar a líderes, equipos y stakeholders a comprender, comprometerse, adoptar y sostener comportamientos y formas de trabajo requeridos por un cambio estratégico u operativo."], ["¿Gestión del Cambio es principalmente comunicación y capacitación?", "No. Ambas importan, pero el cambio duradero también exige alineación, involucramiento, roles claros, capacidades, gobernanza, métricas y refuerzo."], ["¿Qué metodología utilizan?", "Tomamos elementos de Kotter, Prosci ADKAR y prácticas Agile. El método se adapta al reto, contexto y ritmo del cambio en lugar de aplicarse como plantilla rígida."], ["¿Cómo miden la adopción?", "Definimos indicadores por rol como conocimiento, compromiso, readiness, capacidad, comportamiento, uso de procesos, calidad de decisiones y resultados de negocio."], ["¿Puede integrarse Gestión del Cambio a un proyecto de estrategia?", "Sí, y ahí suele crear más valor. Diseñamos implicaciones, alineación de líderes, estrategia de stakeholders y roadmap de adopción junto con la solución estratégica."]],
      conversationTitle: "Tráenos la transformación que no puede quedarse en una presentación.", conversationBody: "En una conversación enfocada de 30 minutos exploraremos el resultado estratégico, las barreras humanas y cómo debe verse la adopción.", whatsapp: "Hola Yuriko, me gustaría conversar sobre un reto de Gestión del Cambio en healthcare con Accesslerate.",
    },
  },
};

export function getStrategicService(locale: ServiceLocale, slug: string) {
  return Object.values(strategicServices).map((service) => service[locale]).find((service) => service?.slug === slug);
}

export function getStrategicServiceSlugs(locale: ServiceLocale) {
  return Object.values(strategicServices).map((service) => service[locale]).filter(Boolean).map((service) => service.slug);
}
