/* Vinext currently breaks next/image at runtime; full-page anchors intentionally switch locale documents. */
/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages */

type Locale = "en" | "es";

const copy = {
  en: {
    lang: "en-US",
    home: "/",
    counterpart: "/es/soluciones/entrada-mercado-healthcare-mexico",
    breadcrumb: ["Home", "Solutions", "Mexico Market Entry"],
    eyebrow: "MEXICO MARKET ENTRY · HEALTHCARE GROWTH · STRATEGY & ACTIVATION",
    title: "Enter Mexico with clarity.",
    accent: "Grow with local advantage.",
    lead: "Operator-led market entry and growth strategy for healthcare companies evaluating, launching or scaling in Mexico.",
    primary: "Discuss your Mexico ambition",
    secondary: "Explore the decisions",
    asideTitle: "One integrated entry agenda",
    aside: ["Market attractiveness and strategic fit", "Access, reimbursement and stakeholder reality", "Partner, channel and route-to-market choices", "Commercial readiness and organizational activation"],
    challengeTitle: "A compelling market does not automatically become a compelling business.",
    challengeBody: "Winning in Mexico requires more than a market report. It requires explicit choices about where to play, how value will be recognized, which route to market fits the opportunity and what the organization must be ready to execute.",
    decisionsTitle: "Six decisions that turn market potential into an executable entry thesis.",
    decisionsLead: "We connect external opportunity with the access, commercial and organizational choices required to capture it.",
    decisions: [["Strategic fit & opportunity", "Clarify why Mexico matters, where the opportunity sits, which assumptions must be true and what success would mean for the broader portfolio."], ["Priority segments & portfolio", "Select the indications, categories, customer segments and opportunity spaces where the company can create distinctive value."], ["Access & value pathway", "Decode public, institutional and private routes; stakeholder value; evidence; affordability; reimbursement and adoption barriers."], ["Entry model & partnering", "Compare direct entry, distributor, licensing, co-commercialization and alliance models against control, speed, economics and capability requirements."], ["Go-to-market & commercial model", "Design customer priorities, channels, coverage, interfaces, capabilities and governance around the chosen opportunity."], ["Organization & change", "Align leaders, decision rights, resources and first-wave behaviors so the market entry moves from recommendation to execution."]],
    momentsTitle: "Built for the moments when the entry decision carries real consequence.",
    moments: [["You are evaluating Mexico from outside the market.", "The opportunity looks attractive, but the organization needs a grounded thesis before committing capital, partners or executive attention."], ["A launch or asset expansion is approaching.", "Access, stakeholder, evidence and commercial assumptions must converge into one credible entry roadmap."], ["A partner or channel decision is at stake.", "You need to know what to retain, what to delegate and which partner can truly activate the opportunity."], ["The current business is not delivering its potential.", "The issue may sit in positioning, access, channels, capabilities, governance—or in the original market thesis itself."]],
    approachTitle: "Local depth. Executive choices. Activation built in.",
    approach: [["Frame", "Define the strategic decision, ambition, investment boundary and evidence required to move."], ["Decode", "Integrate market, access, stakeholder, competitor and organizational realities into a decision-grade view."], ["Choose", "Make explicit choices about priority opportunities, entry model, value logic and route to market."], ["Design", "Build the business case, operating model, capability agenda and sequenced market-entry roadmap."], ["Mobilize", "Align leaders, partners and teams around ownership, governance and measurable first moves."]],
    approachNote: "The scope can be shaped as a focused decision sprint or a staged market-entry engagement.",
    outputsTitle: "A decision system—not a market report.",
    outputsLead: "Every engagement is built around the decision at hand. Typical outputs include:",
    outputs: ["Mexico market-entry thesis and strategic choices", "Opportunity, portfolio and segment prioritization", "Access, stakeholder and value pathway", "Entry-model and partner assessment", "Business case, scenarios and decision risks", "Go-to-market and operating-model blueprint", "Sequenced activation and change roadmap"],
    capabilitiesTitle: "One entry question. Five integrated capabilities.",
    capabilities: [["Business & Growth Strategy", "/services/business-growth-strategy"], ["Market Access", "/services/market-access"], ["New Business & Partnerships", "/services/new-business-partnerships"], ["Commercial Transformation", "/services/commercial-transformation"], ["Change Management", "/services/change-management"]],
    differenceTitle: "Mexico strategy shaped by someone who has operated inside the market.",
    differenceBody: "Accesslerate combines external objectivity with the judgment of a healthcare operator. Yuriko Tovar brings more than 20 years leading growth, market access, commercial operations, patient solutions and transformation across Mexico and Latin America. She remains directly involved from the first question to the activation roadmap.",
    proof: [["20+", "Years across healthcare"], ["7", "Global healthcare companies"], ["5", "Healthcare sectors"]],
    proofNote: "Operator experience spans Pharma, Biotech, Consumer Health, MedTech and Diagnostics.",
    faqTitle: "What healthcare leaders ask before entering Mexico.",
    faq: [["What does a healthcare market-entry engagement include?", "The scope can include market attractiveness, opportunity and portfolio prioritization, access and stakeholder pathways, entry-model scenarios, partner assessment, business case, go-to-market design, organizational readiness and an activation roadmap."], ["Do you recommend direct entry or a local partner?", "There is no universal answer. We compare models against the opportunity, desired control, economics, speed, regulatory and access requirements, internal capabilities and the role a partner must play beyond distribution."], ["How early should Market Access be included?", "From the beginning. Access, evidence, value, affordability and stakeholder adoption shape the real addressable opportunity and should inform the entry thesis—not be added after the commercial plan."], ["Which healthcare sectors do you support?", "Accesslerate works across Pharma, Biotech, Consumer Health, MedTech, Diagnostics, Health Services and investor-backed healthcare opportunities."], ["Can this work connect Mexico with a Latin America strategy?", "Yes. We can build a Mexico-specific entry thesis, compare markets across Latin America or use Mexico as part of a regional sequencing and portfolio decision."], ["How does an engagement begin?", "We start by framing the decision, existing assumptions, available evidence, stakeholders and investment boundary. The work can then take shape as a focused sprint or a staged engagement through activation."]],
    conversationTitle: "Bring us the Mexico question that must be right before resources move.",
    conversationBody: "In a focused 30-minute conversation, we will explore the opportunity, the decisions at stake and whether Accesslerate is the right partner for your market-entry agenda.",
    whatsapp: "Hello Yuriko, I would like to discuss a healthcare market-entry or growth opportunity in Mexico with Accesslerate.",
  },
  es: {
    lang: "es-MX",
    home: "/es",
    counterpart: "/solutions/healthcare-market-entry-mexico",
    breadcrumb: ["Inicio", "Soluciones", "Entrada al Mercado Mexicano"],
    eyebrow: "ENTRADA A MÉXICO · CRECIMIENTO HEALTHCARE · ESTRATEGIA Y ACTIVACIÓN",
    title: "Entra a México con claridad.",
    accent: "Crece con ventaja local.",
    lead: "Estrategia de entrada y crecimiento liderada por operadores para compañías de healthcare que evalúan, lanzan o escalan en México.",
    primary: "Conversemos sobre tu ambición en México",
    secondary: "Conoce las decisiones",
    asideTitle: "Una agenda integrada de entrada",
    aside: ["Atractivo de mercado y fit estratégico", "Realidad de acceso, reembolso y stakeholders", "Decisiones de socios, canales y route-to-market", "Preparación comercial y activación organizacional"],
    challengeTitle: "Un mercado atractivo no se convierte automáticamente en un negocio atractivo.",
    challengeBody: "Ganar en México exige más que un reporte de mercado. Requiere decisiones explícitas sobre dónde jugar, cómo se reconocerá el valor, qué ruta al mercado corresponde a la oportunidad y qué debe estar lista para ejecutar la organización.",
    decisionsTitle: "Seis decisiones que convierten el potencial de mercado en una tesis de entrada ejecutable.",
    decisionsLead: "Conectamos la oportunidad externa con las decisiones de acceso, comerciales y organizacionales necesarias para capturarla.",
    decisions: [["Fit estratégico y oportunidad", "Aclarar por qué México importa, dónde está la oportunidad, qué supuestos deben cumplirse y qué significaría el éxito para el portafolio."], ["Segmentos y portafolio prioritarios", "Seleccionar indicaciones, categorías, clientes y espacios de oportunidad donde la compañía pueda crear valor distintivo."], ["Ruta de acceso y valor", "Decodificar rutas públicas, institucionales y privadas; valor para stakeholders; evidencia; asequibilidad; reembolso y barreras de adopción."], ["Modelo de entrada y alianzas", "Comparar entrada directa, distribución, licenciamiento, co-comercialización y alianzas según control, velocidad, economía y capacidades."], ["Go-to-market y modelo comercial", "Diseñar clientes prioritarios, canales, cobertura, interfaces, capacidades y gobernanza alrededor de la oportunidad elegida."], ["Organización y cambio", "Alinear líderes, decisiones, recursos y primeros comportamientos para llevar la entrada de la recomendación a la ejecución."]],
    momentsTitle: "Diseñado para momentos en los que la decisión de entrada tiene consecuencias reales.",
    moments: [["Estás evaluando México desde fuera del mercado.", "La oportunidad parece atractiva, pero la organización necesita una tesis sólida antes de comprometer capital, socios o atención ejecutiva."], ["Se acerca un lanzamiento o expansión de activo.", "Los supuestos de acceso, stakeholders, evidencia y modelo comercial deben converger en un roadmap creíble."], ["Está en juego una decisión de socio o canal.", "Necesitas saber qué conservar, qué delegar y qué socio puede realmente activar la oportunidad."], ["El negocio actual no entrega su potencial.", "La causa puede estar en posicionamiento, acceso, canales, capacidades, gobernanza o incluso en la tesis original de mercado."]],
    approachTitle: "Profundidad local. Decisiones ejecutivas. Activación incorporada.",
    approach: [["Enmarcar", "Definir la decisión, ambición, límite de inversión y evidencia necesaria para avanzar."], ["Decodificar", "Integrar realidades de mercado, acceso, stakeholders, competencia y organización en una visión útil para decidir."], ["Elegir", "Tomar decisiones explícitas sobre oportunidades, modelo de entrada, lógica de valor y route-to-market."], ["Diseñar", "Construir business case, modelo operativo, agenda de capacidades y roadmap secuenciado."], ["Movilizar", "Alinear líderes, socios y equipos alrededor de ownership, gobernanza y primeros movimientos medibles."]],
    approachNote: "El alcance puede tomar forma de sprint ejecutivo o de un proyecto escalonado de entrada al mercado.",
    outputsTitle: "Un sistema de decisión, no un reporte de mercado.",
    outputsLead: "Cada proyecto se diseña alrededor de la decisión. Los entregables típicos incluyen:",
    outputs: ["Tesis de entrada a México y decisiones estratégicas", "Priorización de oportunidades, portafolio y segmentos", "Ruta de acceso, stakeholders y propuesta de valor", "Evaluación de modelo de entrada y socios", "Business case, escenarios y riesgos de decisión", "Blueprint de go-to-market y modelo operativo", "Roadmap secuenciado de activación y cambio"],
    capabilitiesTitle: "Una pregunta de entrada. Cinco capacidades integradas.",
    capabilities: [["Estrategia de Negocio y Crecimiento", "/es/servicios/estrategia-negocio-crecimiento"], ["Market Access", "/es/servicios/market-access"], ["Nuevos Negocios y Alianzas", "/es/servicios/nuevos-negocios-alianzas"], ["Transformación Comercial", "/es/servicios/transformacion-comercial"], ["Gestión del Cambio", "/es/servicios/gestion-del-cambio"]],
    differenceTitle: "Estrategia para México diseñada por quien ha operado dentro del mercado.",
    differenceBody: "Accesslerate combina objetividad externa con criterio de operadora. Yuriko Tovar aporta más de 20 años liderando crecimiento, market access, operaciones comerciales, soluciones para pacientes y transformación en México y Latinoamérica. Participa directamente desde la primera pregunta hasta el roadmap de activación.",
    proof: [["20+", "Años en healthcare"], ["7", "Compañías globales de healthcare"], ["5", "Sectores de healthcare"]],
    proofNote: "La experiencia operativa abarca Pharma, Biotech, Consumer Health, MedTech y Diagnóstico.",
    faqTitle: "Lo que preguntan los líderes antes de entrar a México.",
    faq: [["¿Qué incluye un proyecto de entrada al mercado healthcare?", "Puede incluir atractivo de mercado, priorización de oportunidades y portafolio, rutas de acceso y stakeholders, escenarios de entrada, evaluación de socios, business case, diseño go-to-market, readiness organizacional y roadmap de activación."], ["¿Recomiendan entrada directa o un socio local?", "No existe una respuesta universal. Comparamos modelos según oportunidad, control deseado, economía, velocidad, requisitos regulatorios y de acceso, capacidades internas y el papel que debe jugar un socio más allá de la distribución."], ["¿Qué tan temprano debe integrarse Market Access?", "Desde el principio. Acceso, evidencia, valor, asequibilidad y adopción determinan la oportunidad realmente capturable y deben informar la tesis de entrada, no agregarse después del plan comercial."], ["¿Con qué sectores de healthcare trabajan?", "Accesslerate trabaja con Pharma, Biotech, Consumer Health, MedTech, Diagnóstico, Servicios de Salud y oportunidades respaldadas por inversionistas."], ["¿Este trabajo puede conectar México con una estrategia regional?", "Sí. Podemos construir una tesis específica para México, comparar mercados latinoamericanos o integrar México a una decisión regional de secuencia y portafolio."], ["¿Cómo comienza un proyecto?", "Comenzamos enmarcando la decisión, supuestos, evidencia disponible, stakeholders y límite de inversión. El trabajo puede tomar forma de sprint enfocado o de un proyecto escalonado hasta la activación."]],
    conversationTitle: "Tráenos la pregunta sobre México que debe estar resuelta antes de mover recursos.",
    conversationBody: "En una conversación enfocada de 30 minutos exploraremos la oportunidad, las decisiones en juego y si Accesslerate es el socio adecuado para tu agenda de entrada al mercado.",
    whatsapp: "Hola Yuriko, me gustaría conversar sobre una oportunidad de entrada o crecimiento en healthcare en México con Accesslerate.",
  },
} as const;

export default function MarketEntrySolutionPage({ locale }: { locale: Locale }) {
  const c = copy[locale];
  const pagePath = locale === "en" ? "/solutions/healthcare-market-entry-mexico" : "/es/soluciones/entrada-mercado-healthcare-mexico";
  const pageUrl = `https://www.accesslerate.com${pagePath}`;
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "Service", "@id": `${pageUrl}#service`, name: locale === "en" ? "Healthcare Market Entry Strategy Mexico" : "Estrategia de Entrada al Mercado Healthcare en México", serviceType: "Healthcare Market Entry and Growth Strategy", url: pageUrl, description: c.lead, areaServed: { "@type": "Country", name: "Mexico" }, provider: { "@type": "ProfessionalService", "@id": "https://www.accesslerate.com/#organization", name: "Accesslerate", url: "https://www.accesslerate.com/" }, audience: { "@type": "BusinessAudience", audienceType: "International and regional healthcare leaders evaluating entry, launch or growth in Mexico" } },
    { "@type": "BreadcrumbList", itemListElement: c.breadcrumb.map((name, index) => ({ "@type": "ListItem", position: index + 1, name, item: index === 0 ? `https://www.accesslerate.com${c.home === "/" ? "/" : c.home}` : index === 2 ? pageUrl : undefined })) },
    { "@type": "FAQPage", mainEntity: c.faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  ] };
  return <main className="service-page" lang={c.lang}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <nav className="nav shell" aria-label={locale === "en" ? "Primary navigation" : "Navegación principal"}>
      <a className="brand brand-logo" href={c.home} aria-label="Accesslerate, home"><img src="/accesslerate-logo-transparent.png" width="792" height="361" alt="Accesslerate" fetchPriority="high" /></a>
      <div className="nav-links"><a href="#decisions">{locale === "en" ? "Entry decisions" : "Decisiones de entrada"}</a><a href="#approach">{locale === "en" ? "Approach" : "Enfoque"}</a><a href="#faq">FAQ</a></div>
      <a className="language-switch" href={c.counterpart} hrefLang={locale === "en" ? "es" : "en"}>{locale === "en" ? "ES" : "EN"}</a>
      <a className="nav-cta" href="#conversation">{locale === "en" ? "Schedule a conversation" : "Agenda una conversación"} <span className="icon-arrow icon-ne" aria-hidden="true" /></a>
    </nav>
    <div className="shell service-breadcrumb"><a href={c.home}>{c.breadcrumb[0]}</a><span>/</span><span>{c.breadcrumb[1]}</span><span>/</span><strong>{c.breadcrumb[2]}</strong></div>
    <section className="shell service-hero" id="top"><div className="service-hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1>{c.title}<br /><em>{c.accent}</em></h1><p className="lead">{c.lead}</p><div className="hero-actions"><a className="button primary" href="#conversation">{c.primary} <span className="icon-arrow" aria-hidden="true" /></a><a className="text-link" href="#decisions">{c.secondary} <span className="icon-arrow icon-down" aria-hidden="true" /></a></div></div><aside className="service-hero-aside"><p>{c.asideTitle}</p><ol>{c.aside.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></aside></section>
    <section className="dark-section service-challenge"><div className="shell service-challenge-grid"><p className="section-index">01 / {locale === "en" ? "THE ENTRY QUESTION" : "LA PREGUNTA DE ENTRADA"}</p><div><h2>{c.challengeTitle}</h2><p>{c.challengeBody}</p></div></div></section>

    <section className="shell service-capabilities section-pad" id="decisions"><header className="service-section-head"><div><p className="section-index">02 / {locale === "en" ? "THE ENTRY DECISIONS" : "LAS DECISIONES DE ENTRADA"}</p><h2>{c.decisionsTitle}</h2></div><p>{c.decisionsLead}</p></header><div className="capability-list">{c.decisions.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="paper-section service-moments"><div className="shell section-pad"><header className="service-section-head"><div><p className="section-index">03 / {locale === "en" ? "WHEN WE HELP" : "CUÁNDO AYUDAMOS"}</p><h2>{c.momentsTitle}</h2></div></header><div className="service-moments-grid">{c.moments.map(([title, body], index) => <article key={title}><span>{String.fromCharCode(65 + index)}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>

    <section className="dark-section service-approach" id="approach"><div className="shell section-pad"><header className="service-section-head light"><div><p className="section-index">04 / {locale === "en" ? "OUR APPROACH" : "NUESTRO ENFOQUE"}</p><h2>{c.approachTitle}</h2></div></header><div className="service-steps">{c.approach.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="service-method">{c.approachNote}</p></div></section>

    <section className="shell service-deliverables section-pad"><div><p className="section-index">05 / {locale === "en" ? "DECISION-GRADE OUTPUTS" : "ENTREGABLES PARA DECIDIR"}</p><h2>{c.outputsTitle}</h2><p className="service-large-copy">{c.outputsLead}</p></div><ol>{c.outputs.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></section>

    <section className="service-related dark-section"><div className="shell section-pad"><p className="section-index">06 / {locale === "en" ? "INTEGRATED CAPABILITIES" : "CAPACIDADES INTEGRADAS"}</p><h2 className="solution-capabilities-title">{c.capabilitiesTitle}</h2><div className="service-related-list">{c.capabilities.map(([label, href], index) => <a href={href} key={href}><span>{String(index + 1).padStart(2, "0")}</span>{label}<i className="icon-arrow icon-ne" aria-hidden="true" /></a>)}</div></div></section>

    <section className="service-difference paper-section"><div className="shell section-pad"><div className="service-difference-grid"><div><p className="section-index">07 / {locale === "en" ? "WHY ACCESSLERATE" : "POR QUÉ ACCESSLERATE"}</p><h2>{c.differenceTitle}</h2></div><p className="service-large-copy">{c.differenceBody}</p></div><div className="service-proof">{c.proof.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><p className="service-proof-note">{c.proofNote}</p></div></section>

    <section className="shell service-faq section-pad" id="faq"><header className="service-section-head"><div><p className="section-index">08 / {locale === "en" ? "FREQUENTLY ASKED QUESTIONS" : "PREGUNTAS FRECUENTES"}</p><h2>{c.faqTitle}</h2></div></header><div className="faq-list">{c.faq.map(([question, answer], index) => <details key={question} open={index === 0}><summary><span>{String(index + 1).padStart(2, "0")}</span>{question}<i aria-hidden="true">+</i></summary><p>{answer}</p></details>)}</div></section>

    <section className="schedule service-conversation" id="conversation"><div className="shell service-conversation-grid"><div><p className="section-index">09 / {locale === "en" ? "START A CONVERSATION" : "INICIA UNA CONVERSACIÓN"}</p><h2>{c.conversationTitle}</h2><p>{c.conversationBody}</p></div><div className="service-contact-card"><a className="button primary wide" href="https://calendly.com/yuriko-accesslerate/30min" target="_blank" rel="noreferrer">{locale === "en" ? "Schedule on Calendly" : "Agendar en Calendly"} <span className="icon-arrow icon-ne" aria-hidden="true" /></a><p>{locale === "en" ? "Or email Yuriko directly" : "O escribe directamente a Yuriko"}</p><a href="mailto:yuriko@accesslerate.com">yuriko@accesslerate.com <span className="icon-arrow icon-ne" aria-hidden="true" /></a><a href={`https://wa.me/525549679335?text=${encodeURIComponent(c.whatsapp)}`} target="_blank" rel="noreferrer">WhatsApp <span className="icon-arrow icon-ne" aria-hidden="true" /></a></div></div></section>

    <footer><div className="shell footer-grid"><div><a className="brand brand-logo footer-brand" href={c.home}><img src="/accesslerate-logo-footer.png" width="792" height="361" alt="Accesslerate" loading="lazy" /></a><p>Complexity Shapes Advantage.</p></div><div><p>{locale === "en" ? "Operator-led healthcare strategy across Mexico and Latin America." : "Estrategia healthcare liderada por operadores en México y Latinoamérica."}</p><div className="footer-language"><a href="/" hrefLang="en">English</a><span>/</span><a href="/es" hrefLang="es">Español</a></div></div><div><a href={c.home}>{locale === "en" ? "Back to Accesslerate" : "Volver a Accesslerate"}</a><a href="#decisions">{locale === "en" ? "Entry decisions" : "Decisiones de entrada"}</a><a href="#approach">{locale === "en" ? "Approach" : "Enfoque"}</a><a href="#conversation">{locale === "en" ? "Start a conversation" : "Inicia una conversación"}</a></div></div><div className="shell legal"><span>© {new Date().getFullYear()} Accesslerate. {locale === "en" ? "All rights reserved." : "Todos los derechos reservados."}</span><a href="#top">{locale === "en" ? "Back to top" : "Volver arriba"} <span className="icon-arrow icon-up" aria-hidden="true" /></a></div></footer>
  </main>;
}
