/* Vinext currently breaks next/image at runtime; full-page anchors intentionally switch locale documents. */
/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages */
import type { StrategicServiceCopy } from "../lib/strategic-services";

export default function StrategicServicePage({ service }: { service: StrategicServiceCopy }) {
  const isEnglish = service.locale === "en";
  const home = isEnglish ? "/" : "/es";
  const counterpart = isEnglish ? `/es/servicios/${service.counterpartSlug}` : `/services/${service.counterpartSlug}`;
  const pagePath = isEnglish ? `/services/${service.slug}` : `/es/servicios/${service.slug}`;
  const pageUrl = `https://www.accesslerate.com${pagePath}`;
  const related = isEnglish ? [
    ["Business & Growth Strategy", "/services/business-growth-strategy"], ["Market Access", "/services/market-access"], ["New Business & Partnerships", "/services/new-business-partnerships"], ["Commercial Transformation", "/services/commercial-transformation"], ["Change Management", "/services/change-management"],
  ] : [
    ["Estrategia de Negocio y Crecimiento", "/es/servicios/estrategia-negocio-crecimiento"], ["Market Access", "/es/servicios/market-access"], ["Nuevos Negocios y Alianzas", "/es/servicios/nuevos-negocios-alianzas"], ["Transformación Comercial", "/es/servicios/transformacion-comercial"], ["Gestión del Cambio", "/es/servicios/gestion-del-cambio"],
  ];
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "Service", "@id": `${pageUrl}#service`, name: service.schemaName, serviceType: service.schemaType, url: pageUrl, description: service.seoDescription, areaServed: [{ "@type": "Country", name: "Mexico" }, { "@type": "Place", name: "Latin America" }], provider: { "@type": "ProfessionalService", "@id": "https://www.accesslerate.com/#organization", name: "Accesslerate", url: "https://www.accesslerate.com/" }, audience: { "@type": "BusinessAudience", audienceType: "Healthcare leaders, Pharma, Biotech, Consumer Health, MedTech, Diagnostics, Health Services and investors" } },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: isEnglish ? "Home" : "Inicio", item: `https://www.accesslerate.com${home === "/" ? "/" : home}` }, { "@type": "ListItem", position: 2, name: isEnglish ? "Expertise" : "Servicios" }, { "@type": "ListItem", position: 3, name: service.breadcrumb, item: pageUrl }] },
    { "@type": "FAQPage", mainEntity: service.faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  ] };

  return <main className="service-page" lang={isEnglish ? "en-US" : "es-MX"}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <nav className="nav shell" aria-label={isEnglish ? "Primary navigation" : "Navegación principal"}>
      <a className="brand brand-logo" href={home} aria-label="Accesslerate, home"><img src="/accesslerate-logo-transparent.png" width="792" height="361" alt="Accesslerate" fetchPriority="high" /></a>
      <div className="nav-links"><a href="#capabilities">{isEnglish ? "Capabilities" : "Capacidades"}</a><a href="#approach">{isEnglish ? "Approach" : "Enfoque"}</a><a href="#faq">FAQ</a></div>
      <a className="language-switch" href={counterpart} hrefLang={isEnglish ? "es" : "en"}>{isEnglish ? "ES" : "EN"}</a>
      <a className="nav-cta" href="#conversation">{isEnglish ? "Schedule a conversation" : "Agenda una conversación"} <span className="icon-arrow icon-ne" aria-hidden="true" /></a>
    </nav>
    <div className="shell service-breadcrumb"><a href={home}>{isEnglish ? "Home" : "Inicio"}</a><span>/</span><span>{isEnglish ? "Expertise" : "Servicios"}</span><span>/</span><strong>{service.breadcrumb}</strong></div>
    <section className="shell service-hero" id="top"><div className="service-hero-copy"><p className="eyebrow">{service.eyebrow}</p><h1>{service.title}<br /><em>{service.accent}</em></h1><p className="lead">{service.lead}</p><div className="hero-actions"><a className="button primary" href="#conversation">{service.primary} <span className="icon-arrow" aria-hidden="true" /></a><a className="text-link" href="#capabilities">{isEnglish ? "Explore our capabilities" : "Conoce nuestras capacidades"} <span className="icon-arrow icon-down" aria-hidden="true" /></a></div></div><aside className="service-hero-aside"><p>{service.asideTitle}</p><ol>{service.aside.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></aside></section>
    <section className="dark-section service-challenge"><div className="shell service-challenge-grid"><p className="section-index">01 / {isEnglish ? "THE CHALLENGE" : "EL RETO"}</p><div><h2>{service.challengeTitle}</h2><p>{service.challengeBody}</p></div></div></section>

    <section className="shell service-capabilities section-pad" id="capabilities"><header className="service-section-head"><div><p className="section-index">02 / {isEnglish ? "WHERE WE HELP" : "DÓNDE AYUDAMOS"}</p><h2>{service.capabilitiesTitle}</h2></div><p>{service.capabilitiesLead}</p></header><div className="capability-list">{service.capabilities.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="paper-section service-moments"><div className="shell section-pad"><header className="service-section-head"><div><p className="section-index">03 / {isEnglish ? "CRITICAL MOMENTS" : "MOMENTOS CRÍTICOS"}</p><h2>{service.momentsTitle}</h2></div></header><div className="service-moments-grid">{service.moments.map(([title, body], index) => <article key={title}><span>{String.fromCharCode(65 + index)}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>

    <section className="dark-section service-approach" id="approach"><div className="shell section-pad"><header className="service-section-head light"><div><p className="section-index">04 / {isEnglish ? "OUR APPROACH" : "NUESTRO ENFOQUE"}</p><h2>{service.approachTitle}</h2></div></header><div className="service-steps">{service.approach.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="service-method">{service.methodNote}</p></div></section>

    <section className="shell service-deliverables section-pad"><div><p className="section-index">05 / {isEnglish ? "TANGIBLE OUTPUTS" : "ENTREGABLES TANGIBLES"}</p><h2>{service.deliverablesTitle}</h2><p className="service-large-copy">{isEnglish ? "Every engagement is shaped around the decision at hand. Typical outputs include:" : "Cada proyecto se diseña alrededor de la decisión. Los entregables típicos incluyen:"}</p></div><ol>{service.deliverables.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></section>

    <section className="service-difference paper-section"><div className="shell section-pad"><div className="service-difference-grid"><div><p className="section-index">06 / {isEnglish ? "WHY ACCESSLERATE" : "POR QUÉ ACCESSLERATE"}</p><h2>{service.differenceTitle}</h2></div><p className="service-large-copy">{service.differenceBody}</p></div><p className="proof-note">{isEnglish ? "Selected operator perspective" : "Perspectiva operativa seleccionada"}</p><div className="service-proof">{service.proof.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><p className="service-proof-note">{service.proofNote}</p></div></section>

    <section className="shell service-faq section-pad" id="faq"><header className="service-section-head"><div><p className="section-index">07 / {isEnglish ? "FREQUENTLY ASKED QUESTIONS" : "PREGUNTAS FRECUENTES"}</p><h2>{isEnglish ? "Questions healthcare leaders ask us." : "Lo que nos preguntan los líderes de healthcare."}</h2></div></header><div className="faq-list">{service.faq.map(([question, answer], index) => <details key={question} open={index === 0}><summary><span>{String(index + 1).padStart(2, "0")}</span>{question}<i aria-hidden="true">+</i></summary><p>{answer}</p></details>)}</div></section>

    <section className="service-related dark-section"><div className="shell section-pad"><p className="section-index">{isEnglish ? "EXPLORE OUR EXPERTISE" : "CONOCE NUESTROS SERVICIOS"}</p><a className="service-solution-callout" href={isEnglish ? "/solutions/healthcare-market-entry-mexico" : "/es/soluciones/entrada-mercado-healthcare-mexico"}><span>{isEnglish ? "FEATURED SOLUTION" : "SOLUCIÓN DESTACADA"}</span><strong>{isEnglish ? "Healthcare Market Entry & Growth Strategy in Mexico" : "Estrategia de Entrada y Crecimiento Healthcare en México"}</strong><i className="icon-arrow icon-ne" aria-hidden="true" /></a><div className="service-related-list">{related.map(([label, href], index) => <a href={href} key={href} aria-current={href === pagePath ? "page" : undefined}><span>{String(index + 1).padStart(2, "0")}</span>{label}<i className="icon-arrow icon-ne" aria-hidden="true" /></a>)}</div></div></section>

    <section className="schedule service-conversation" id="conversation"><div className="shell service-conversation-grid"><div><p className="section-index">08 / {isEnglish ? "START A CONVERSATION" : "INICIA UNA CONVERSACIÓN"}</p><h2>{service.conversationTitle}</h2><p>{service.conversationBody}</p></div><div className="service-contact-card"><a className="button primary wide" href="https://calendly.com/yuriko-accesslerate/30min" target="_blank" rel="noreferrer">{isEnglish ? "Schedule on Calendly" : "Agendar en Calendly"} <span className="icon-arrow icon-ne" aria-hidden="true" /></a><p>{isEnglish ? "Or email Yuriko directly" : "O escribe directamente a Yuriko"}</p><a href="mailto:yuriko@accesslerate.com">yuriko@accesslerate.com <span className="icon-arrow icon-ne" aria-hidden="true" /></a><a href={`https://wa.me/525549679335?text=${encodeURIComponent(service.whatsapp)}`} target="_blank" rel="noreferrer">WhatsApp <span className="icon-arrow icon-ne" aria-hidden="true" /></a></div></div></section>

    <footer><div className="shell footer-grid"><div><a className="brand brand-logo footer-brand" href={home}><img src="/accesslerate-logo-footer.png" width="792" height="361" alt="Accesslerate" loading="lazy" /></a><p>Complexity Shapes Advantage.</p></div><div><p>{isEnglish ? "Operator-led healthcare strategy across Mexico and Latin America." : "Estrategia healthcare liderada por operadores en México y Latinoamérica."}</p><div className="footer-language"><a href="/" hrefLang="en">English</a><span>/</span><a href="/es" hrefLang="es">Español</a></div></div><div><a href={home}>{isEnglish ? "Back to Accesslerate" : "Volver a Accesslerate"}</a><a href="#capabilities">{isEnglish ? "Capabilities" : "Capacidades"}</a><a href="#approach">{isEnglish ? "Approach" : "Enfoque"}</a><a href="#conversation">{isEnglish ? "Start a conversation" : "Inicia una conversación"}</a></div></div><div className="shell legal"><span>© {new Date().getFullYear()} Accesslerate. {isEnglish ? "All rights reserved." : "Todos los derechos reservados."}</span><a href="#top">{isEnglish ? "Back to top" : "Volver arriba"} <span className="icon-arrow icon-up" aria-hidden="true" /></a></div></footer>
  </main>;
}
